### ISSUE TITLE
New version C++ is not compiling 

### ISSUE THREAD

**Issue by oredi** [merelin/mediasmartserverd#10]
Hi,

I was trying to compile the code using gcc version 6.3.0 20170516 (Debian 6.3.0-18) but I was getting the following error
`
rm *.o mediasmartserverd core -f
g++ -Wall -O2 -o device_monitor.o -c src/device_monitor.cpp
g++ -Wall -O2 -o update_monitor.o -c src/update_monitor.cpp -pthread
src/update_monitor.cpp: In static member function ‘static bool UpdateMonitor::IsRebootRequired()’:
src/update_monitor.cpp:273:9: error: cannot convert ‘std::ifstream {aka std::basic_ifstream<char>}’ to ‘bool’ in return
  return reboot_required; //Returns whether file exists.
         ^~~~~~~~~~~~~~~
Makefile:21: recipe for target 'update_monitor.o' failed
make: *** [update_monitor.o] Error 1
`

I think the following code is causing the problem
`
	/**
	 * Checks if reboot is required.
	 * @return Returns true if reboot is required.
	 * @private @static
	 */
	bool UpdateMonitor::IsRebootRequired()
	{
		std::ifstream reboot_required("/var/run/reboot-required");
		return reboot_required; //Returns whether file exists.
	}
`

I appears to be related to the new versions of C++ listed in -> https://stackoverflow.com/questions/6242768/is-the-safe-bool-idiom-obsolete-in-c11

Is this something that can be fixed.

Thanks for your attention

**Comment by merelin** [comment]
@oredi Hi, sorry for the late response. I did fix the issue a while ago. Have just committed and pushed the fix. Could you please give it another try? Thanks!
