### ISSUE TITLE
Segmentation fault on Gentoo (latest git)

### ISSUE THREAD

**Issue by vovan69** [merelin/mediasmartserverd#3]
The daemon works just fine. However I have "segmentation fault" when adding/removing HDD's. IMO it could be something to do with the newer version of udev:
- vanilla kernel 3.12.9
- udev/systemd 208

**Comment by merelin** [comment]
Hi, I would suggest that you grab the sources and play with them to fix the issue for Gentoo. Then please raise a PR.
