### ISSUE TITLE
Update info for HP EX495

### ISSUE THREAD

**Issue by ThermoMan** [merelin/mediasmartserverd#8]
Hi, grabbed your software for my HP EX495 now that I have installed Ubuntu.  I thik I am going to find it terrifically useful.  Thanks.

I'll try to submit a code update soon, but for now I have the values for identification.  Until I get that code submitted I hope someone finds this info useful.
    const char *systemVendor = GetUdevDeviceAttribute("dmi", "id", "sys_vendor");
    const char *productName = GetUdevDeviceAttribute("dmi", "id", "product_name");

I found these by reading the file system /sys/devices/virtual/dmi/id directory
Under /sys/devices/virtual/dmi/id
bios_date = 07/23/2009
bios_vendor = American Megatrends Inc.
bios_version = EX49x 1.00
board_asset_tag =
board_name = 532837-ZH1
board_serial = 532837-ZH1--board serial number here--
board_vendor = Wistron
board_version = A
chassis_asset_tag =
chassis_serial = --chassis serial number here--
chassis_type = 3
chassis_vendor = HP
chassis_version = A
modalias = dmi:bvnAmericanMegatrendsInc.:bvrEX49x1.00:bd07/23/2009:svnHP:pnMediaSmartServer:pvrA:rvnWistron:rn532837-ZH1:rvrA:cvnHP:ct3:cvrA:
**product_name = MediaSmart Server**
product_serial = --chassis number here--
product_uuid = --uuid number here--
product_version = A
**sys_vendor = HP**
uevent = MODALIAS=dmi:bvnAmericanMegatrendsInc.:bvrEX49x1.00:bd07/23/2009:svnHP:pnMediaSmartServer:pvrA:rvnWistron:rn532837-ZH1:rvrA:cvnHP:ct3:cvrA:

Under  /sys/devices/virtual/dmi/id/power
async = disabled
autosuspend_delay_ms =
control = auto
runtime_active_kids = 0
runtime_active_time = 0
runtime_enabled = disabled
runtime_status = unsupported
runtime_suspended_time = 0
runtime_usage = 0

Additionally the for the chip info should be updated.  SMSC got bought out.
http://www.microchip.com/wwwproducts/en/SCH5127#documentation

**Comment by merelin** [comment]
Hi, are you going to raise a PR?
